# Generated by Django 2.0.3 on 2018-03-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
